git commit -m "edited nav bar"
cop4331-12/cop4331-contact-manager pull request #17
Opened 2021-05-23 01:06 UTC by gexrgia

2021-05-23 01:06 UTC, VijayStroup requested changes
add styling

2021-05-25 17:54 UTC, VijayStroup requested changes

2021-05-25 17:54 UTC, VijayStroup commented on templates/base.html
> +      <li class="nav-item"><a href="/Contacts">Contacts</a></li>
the href should be `/contacts` lowercase.

2021-05-25 17:54 UTC, VijayStroup commented on templates/base.html
> -  <main>{% block main %}{% endblock %}</main>
This line is not to be deleted.

2021-05-25 17:54 UTC, VijayStroup commented on templates/main.css
> +body {
transfer these stylings to the css file located in static/main.css and then delete this file.

2021-05-25 17:54 UTC, VijayStroup commented on templates/base.html
> +  <link rel="stylesheet" href="/home/gnewbery/cop4331-contact-manager/templates/main.css">
delete this line.

2021-05-25 17:54 UTC, VijayStroup commented on templates/base.html
> -  <link rel="shortcut icon" href="{{ url_for('static', path='/favicon.ico') }}" type="image/x-icon">
this is the image located in the tab when you visit the website, it should have not been deleted.

2021-05-25 17:54 UTC, VijayStroup commented on templates/base.html
> -  <link href="{{ url_for('static', path='/main.css') }}" rel="stylesheet">
This is the link to the style sheet in the static folder instead of your link you made that is specific to only your path.
It should have not been deleted.

2021-05-25 17:56 UTC, gexrgia commented on templates/base.html
> -  <main>{% block main %}{% endblock %}</main>
Okay, what does it do? When I tired it locally it showed up as text on the page.

2021-05-25 18:10 UTC, VijayStroup commented on templates/base.html
> -  <main>{% block main %}{% endblock %}</main>
we declare a "block" main where when we extend this base file, we can populate the block.

2021-05-25 18:14 UTC, VijayStroup approved these changes
Looks good :)

2021-05-25 18:15 UTC, merged