User DB methods and API Routes
cop4331-12/cop4331-contact-manager pull request #26
Opened 2021-05-26 21:14 UTC by JayHenry07

Completed db.get_user, db.update_user_activity, db.search, api.login, api.update_contact, and api.search_contacts

2021-05-26 23:38 UTC, VijayStroup requested changes
Note: some comments may also be the same thing in other places.

2021-05-26 23:38 UTC, VijayStroup commented on db.py
> +                WHERE username = (?) AND password = (?)''',
No need for () around (?)

2021-05-26 23:38 UTC, VijayStroup commented on db.py
> +
methods, separate from functions, typically only have 1 blank line, not 2.

2021-05-26 23:38 UTC, VijayStroup commented on db.py
> +            self.con.commit()
do not need to commit with `SELECT` commands

2021-05-26 23:38 UTC, VijayStroup commented on db.py
> +            else: return (user, auth.encode_token(user['id']), 0, None)
I don't think the return will be a dict, it returns is a list.
I recommend you make a user dict from the list that you will be returned which relates to the table schema like this:
```py
user = {
    id=user[0],
    record_created=user[1],
...
    password=user[4]
}

auth.encode_token(user['id'])
```

2021-05-26 23:38 UTC, VijayStroup commented on db.py
> +            return (self.db.fetchone(), None, 500, e)
return `None` for the user here too.

2021-05-26 23:38 UTC, VijayStroup commented on middleware/auth.py
> +
methods have 1 blank line, functions have 2

2021-05-26 23:38 UTC, VijayStroup commented on db.py
> +            return (self.db.fetchall(), 500, e)
return None when getting an error

2021-05-26 23:38 UTC, VijayStroup commented on db.py
> +            self.con.commit()
no need for commit

2021-05-26 23:50 UTC, JayHenry07 commented on db.py
> +            return (self.db.fetchone(), None, 500, e)
Return None for user on line 85 and 86?

2021-05-27 00:55 UTC, VijayStroup commented on db.py
> +            return (self.db.fetchone(), None, 500, e)
No;
If you find the user return (user, jwt, 0, None)
If you dont return (None, None, code, msg)

2021-05-27 01:02 UTC, VijayStroup requested changes

2021-05-27 01:02 UTC, VijayStroup commented on db.py
> +
remove extra line

2021-05-27 01:02 UTC, VijayStroup commented on db.py
> +
remove extra line

2021-05-27 01:02 UTC, VijayStroup commented on db.py
> +
remove extra line

2021-05-27 01:02 UTC, VijayStroup commented on db.py
> +
remove extra line

2021-05-27 01:02 UTC, VijayStroup commented on db.py
> +            return (self.db.fetchall(), 500, e)
still need to return None when we except the error

2021-05-27 01:02 UTC, VijayStroup commented on middleware/auth.py
> +
remove extra line

2021-05-27 01:02 UTC, VijayStroup commented on middleware/auth.py
> +
remove extra line

2021-05-27 03:14 UTC, VijayStroup requested changes

2021-05-27 03:14 UTC, VijayStroup commented on db.py
> +
remove extra line

2021-05-27 03:14 UTC, VijayStroup commented on db.py
> +                username, hash_password(password, username))
bind statements need to be tuples so change the variables you change in to `(username, hash_password(password, username))`

2021-05-27 03:14 UTC, VijayStroup commented on db.py
> +            return (self.db.fetchone(), 0, None)
We don't care about getting user info in this method, you can just return a error and message for both parts

2021-05-27 03:14 UTC, VijayStroup commented on db.py
> +
remove extra line

2021-05-27 03:14 UTC, VijayStroup commented on db.py
> +                WHERE id = ? AND * LIKE %?%''', id, search)
bind statement needs to be an iterable: (id, search)

2021-05-27 15:26 UTC, VijayStroup requested changes

2021-05-27 15:26 UTC, VijayStroup commented on db.py
> +            self.db.execute('''SELECT * FROM user
We are actually searching from the contacts table not the user table but you are using the foreign key to only search contacts associated with that user.

2021-05-27 15:36 UTC, VijayStroup approved these changes

2021-05-27 15:36 UTC, merged